CREATE OR REPLACE VIEW DM_DATASCIENCE.FEEDER_LOAD_PROFILE_VIEW AS
SELECT 
AM.FEEDERNAME AS FEEDERNAME,
US.MINLOAD AS MINLOAD_FEEDER,
US.MAXLOAD AS MAXLOAD_FEEDER,
US.AVGLOAD AS AVGLOAD_FEEDER,
CCF.CUSTOMER_COUNT_FEEDER AS NOOFCUSTOMERSFEEDER,
COALESCE(EV_FEED.EV_COUNT,0) AS FEED_EV_COUNT,
COALESCE(AG_FEED.SYSTEM_CAPACITY_KW,0) AS FEED_PVSIZE
FROM 
(SELECT DISTINCT FEEDERNAME,FEEDERID  FROM WAREHOUSE.HUB_GIS_ASSET_MAP) AM
LEFT JOIN (SELECT SUM(CC.CUSTOMER_COUNT) AS CUSTOMER_COUNT_FEEDER, AM.FEEDERID, AM.FEEDERNAME
        FROM WAREHOUSE.TRANS_CUSTCOUNT CC
        JOIN (SELECT DISTINCT BANK_OBJECTID, FEEDERID, FEEDERNAME
              FROM WAREHOUSE.HUB_GIS_ASSET_MAP) AM
        ON AM.BANK_OBJECTID = CC.TRANSFOMERID
      GROUP BY FEEDERID, FEEDERNAME
     ) CCF --CUSTCOUNT FEEDER
ON CCF.FEEDERID = AM.FEEDERID
LEFT JOIN ( SELECT FEEDER, AVG(AVERAGE_USAGE) AS AVGLOAD,MAX(MAX_USAGE) AS MAXLOAD,MIN(MIN_USAGE) AS MINLOAD
           FROM WAREHOUSE.FEEDER_USAGE_SEASON FUS
          GROUP BY FEEDER) US
ON US.FEEDER = AM.FEEDERID
LEFT JOIN (SELECT FEEDERNAME,COUNT(DISTINCT(VIN_REDUCED)) AS EV_COUNT  FROM EV.CLEAN_EV_ASSET_MAP GROUP BY FEEDERNAME ) EV_FEED
ON AM.FEEDERNAME = EV_FEED.FEEDERNAME
LEFT JOIN (SELECT FEEDERNAME,SUM(SYSTEM_CAPACITY_KW) AS SYSTEM_CAPACITY_KW FROM NEM.SP_ACTIVEGENERATORS 
			WHERE  UPPER(TYPE_OF_GENERATOR) IN ('S', 'S ', 'SOLAR', 'SOLAR ') GROUP BY FEEDERNAME) AG_FEED
ON AM.FEEDERNAME = AG_FEED.FEEDERNAME;