CREATE
OR REPLACE VIEW DM_DATASCIENCE.REPEATED_UNPLANNED_OUTAGE_COUNT AS (
    WITH T1 AS (
        SELECT
            DISTINCT SUBSTR (ALIAS, 8) LABELTEXT,
            BEGIN_TIME
        FROM
            OUTAGEMANAGEMENT.JOBS J
        WHERE
            (BEGIN_TIME >= TO_TIMESTAMP_NTZ('2021-02-26'))
            AND DEVCLS_NAME LIKE 'xfm%'
            AND STATUS != 12
            AND CALL_TYPE NOT IN ('SWP', 'PLAN')
    )
    SELECT
        'REPEATED UNPLANNED' AS OUTAGETYPE,
        A.OBJECTID,
        COUNT(*) COUNT_REPLACED,
        MAX(TO_DATE(T1.BEGIN_TIME)) RECENTOUTAGEDATE,
        A.ACTIVE_FLAG,
		case when ACTIVE_FLAG = 'Y' THEN 'NO LABELTEXT CHANGE IN GIS'
        when ACTIVE_FLAG = 'N' THEN 'LABELTEXT CHANGED IN GIS'
        else 'INFO NOT AVL'
        END as COMMENT
    FROM
        WAREHOUSE.SAT_GIS_TRANSFORMER_PIT A
        INNER JOIN T1 ON A.LABELTEXT = T1.LABELTEXT
        INNER JOIN (
            SELECT
                BANK_OBJECTID
            FROM
                DM_DATASCIENCE.OVERLOADED_TRANSFORMER_YEARLY_SNAPSHOT
            WHERE
                XFMR_OVERLOAD_COUNT <> 0
            GROUP BY
                BANK_OBJECTID
        ) B ON A.OBJECTID = B.BANK_OBJECTID
    GROUP BY
        A.OBJECTID,
        A.ACTIVE_FLAG
    HAVING
        COUNT(*) > 1
);