CREATE
OR REPLACE VIEW DM_DATASCIENCE.REPEATED_UNPLANNED_OUTAGE_DETAILS AS (
    WITH T AS (
        SELECT
            OBJECTID
        FROM
            DM_DATASCIENCE.REPEATED_UNPLANNED_OUTAGE_COUNT
    ),
    T2 AS (
        SELECT
            EVENT_IDX,
            BEGIN_TIME,
            RESTORE_TIME,
            OUTAGE_LENGTH_MIN,
            CUSTCOUNT,
            CMI_MIN,
            BANK_OBJECTID,
            XFMR_OVERLOAD_COUNT,
            OVERLOAD_REPORT_DATE
        FROM
            DM_DATASCIENCE.UNPLANNED_OUTAGE_DETAILS
    )
    SELECT
        'REPEATED UNPLANNED' AS OUTAGETYPE,
        T2.EVENT_IDX,
        T2.BEGIN_TIME,
        T2.RESTORE_TIME,
        T2.BANK_OBJECTID,
        T2.OUTAGE_LENGTH_MIN,
        T2.CUSTCOUNT,
        T2.CMI_MIN,
        T2.XFMR_OVERLOAD_COUNT,
        T2.OVERLOAD_REPORT_DATE
    FROM
        T2
        INNER JOIN T ON T.OBJECTID = T2.BANK_OBJECTID
    ORDER BY
        BANK_OBJECTID
);
