CREATE OR REPLACE VIEW DM_DATASCIENCE.TRANS_LOAD_PROFILE_VIEW AS
SELECT 
AM.BANK_OBJECTID AS BANK_OBJECTID,
AM.LABELTEXT AS LABELTEXT,
T.RATEDKVA AS CAPACITY,
T.HIGHSIDECONFIGURATION AS HIGHCONFIGURATION,
T.LOWSIDECONFIGURATION AS LOWCONFIGURATION,
COALESCE(CCT.CUSTOMER_COUNT,0) AS NOOFCUSTOMERS_TRANS,
CASE WHEN T.PHASEDESIGNATION = 1 THEN 'C'
	 WHEN T.PHASEDESIGNATION = 2 THEN 'B'
	 WHEN T.PHASEDESIGNATION = 3 THEN 'BC'
	 WHEN T.PHASEDESIGNATION = 4 THEN 'A'
	 WHEN T.PHASEDESIGNATION = 5 THEN 'AC'
	 WHEN T.PHASEDESIGNATION = 6 THEN 'AB'
	 WHEN T.PHASEDESIGNATION = 7 THEN 'ABC'
	 END AS PHASE,
COALESCE(EV_TX.EV_COUNT,0) AS TX_EV_COUNT,
COALESCE(AG_TX.SYSTEM_CAPACITY_KW,0) AS TX_PVSIZE,
AM.FEEDERNAME AS FEEDERNAME,
US.MINLOAD AS MINLOAD_FEEDER,
US.MAXLOAD AS MAXLOAD_FEEDER,
US.AVGLOAD AS AVGLOAD_FEEDER,
CCF.CUSTOMER_COUNT_FEEDER AS NOOFCUSTOMERSFEEDER,
COALESCE(EV_FEED.EV_COUNT,0) AS FEED_EV_COUNT,
COALESCE(AG_FEED.SYSTEM_CAPACITY_KW,0) AS FEED_PVSIZE
FROM 
(SELECT DISTINCT BANK_OBJECTID,LABELTEXT,FEEDERNAME,FEEDERID  FROM WAREHOUSE.HUB_GIS_ASSET_MAP) AM
LEFT JOIN (SELECT TRANSFOMERID, CUSTOMER_COUNT
      FROM WAREHOUSE.TRANS_CUSTCOUNT
     ) CCT --CUSTOMERCOUNT TRANSFORMER
ON CCT.TRANSFOMERID = AM.BANK_OBJECTID
LEFT JOIN GEOSPATIAL.TRANSFORMER_EVW T
ON AM.BANK_OBJECTID = T.OBJECTID
LEFT JOIN (SELECT SUM(CC.CUSTOMER_COUNT) AS CUSTOMER_COUNT_FEEDER, AM.FEEDERID, AM.FEEDERNAME
        FROM WAREHOUSE.TRANS_CUSTCOUNT CC
        JOIN (SELECT DISTINCT BANK_OBJECTID, FEEDERID, FEEDERNAME
              FROM WAREHOUSE.HUB_GIS_ASSET_MAP) AM
        ON AM.BANK_OBJECTID = CC.TRANSFOMERID
      GROUP BY FEEDERID, FEEDERNAME
     ) CCF --CUSTCOUNT FEEDER
ON CCF.FEEDERID = AM.FEEDERID
LEFT JOIN ( SELECT FEEDER, AVG(AVERAGE_USAGE) AS AVGLOAD,MAX(MAX_USAGE) AS MAXLOAD,MIN(MIN_USAGE) AS MINLOAD
           FROM WAREHOUSE.FEEDER_USAGE_SEASON FUS
          GROUP BY FEEDER) US
ON US.FEEDER = AM.FEEDERID
LEFT JOIN (SELECT BANK_OBJECTID,COUNT(DISTINCT(VIN_REDUCED)) AS EV_COUNT  FROM EV.CLEAN_EV_ASSET_MAP GROUP BY BANK_OBJECTID ) EV_TX
ON AM.BANK_OBJECTID = EV_TX.BANK_OBJECTID
LEFT JOIN (SELECT FEEDERNAME,COUNT(DISTINCT(VIN_REDUCED)) AS EV_COUNT  FROM EV.CLEAN_EV_ASSET_MAP GROUP BY FEEDERNAME ) EV_FEED
ON AM.FEEDERNAME = EV_FEED.FEEDERNAME
LEFT JOIN (SELECT BANK_OBJECTID,LABELTEXT,SUM(SYSTEM_CAPACITY_KW) AS SYSTEM_CAPACITY_KW FROM NEM.TRANS_ACTIVEGENERATORS TRANS_AG
			 WHERE  UPPER(TYPE_OF_GENERATOR) IN ('S', 'S ', 'SOLAR', 'SOLAR ')
			 GROUP BY BANK_OBJECTID,LABELTEXT) AG_TX
ON AM.BANK_OBJECTID = AG_TX.BANK_OBJECTID
AND AM.LABELTEXT = AG_TX.LABELTEXT
LEFT JOIN (SELECT FEEDERNAME,SUM(SYSTEM_CAPACITY_KW) AS SYSTEM_CAPACITY_KW FROM NEM.SP_ACTIVEGENERATORS 
			WHERE  UPPER(TYPE_OF_GENERATOR) IN ('S', 'S ', 'SOLAR', 'SOLAR ') GROUP BY FEEDERNAME) AG_FEED
ON AM.FEEDERNAME = AG_FEED.FEEDERNAME;