CREATE OR REPLACE VIEW DM_DATASCIENCE.TRANS_CUST_INFO AS
SELECT TRANS.BANK_OBJECTID,LABELTEXT,DESCRIPTION,COUNT FROM
(SELECT BANK_OBJECTID,DESCRIPTION,COUNT(*) AS COUNT FROM DM_DATASCIENCE.LOAD_CUST_INFO
GROUP BY BANK_OBJECTID,DESCRIPTION) TRANS
JOIN (select distinct BANK_OBJECTID,LABELTEXT from WAREHOUSE.HUB_GIS_ASSET_MAP) AM
ON TRANS.BANK_OBJECTID = AM.BANK_OBJECTID 
ORDER BY COUNT DESC;