CREATE OR REPLACE VIEW DM_CRIS.V_CRIS_DEPT_PLAN_SCHEDULE
AS
SELECT	CON."u8dd8_recordcategoryname" AS PATTERN_CODE,
		CON."u3038_fppatterncode" AS FPPATTERN_CODE,
		CON."u5118_officeofrecord" AS OFFICE_OF_RECORD,
		CON."u4308_comments" AS RC_COMMENTS,
		GEN."u7818_disposalschedulename" AS RETENTION_SCHEDULE,
		CON."u8488_fprcnumber" AS RC_NUMBER,
		CON."u448f_rmentitydescription" AS RMENTITY_DESCRIPTION,
		CON."u7688_filingguidelines" AS FILING_GUIDELINES,
		GEN."u99ef_rmentitydescription" AS GENRM_ENTITY_DESCRIPTION
FROM   (CRIS.CONTAINER_PGEP8FPOSPHY CON 
LEFT OUTER JOIN CRIS.GENERIC_PGEP8FPOSPHY GEN 
ON CON."u7437_disposalschedule" = GEN."object_id");