CREATE OR REPLACE VIEW DM_DATASCIENCE.V_LOAD_CLASS_AGG AS 
WITH SUB AS 
(select LOAD_CLASS_ID,PROFILE_GROUP_ID,WEIGHT,row_number() over (partition by LOAD_CLASS_ID order by WEIGHT desc) as row_num from DM_DATASCIENCE.LOAD_CLASS),
TOTAL AS (select LOAD_CLASS_ID,sum(WEIGHT) as TOTAL_WEIGHT from SUB
where row_num > 4 
group by LOAD_CLASS_ID)
select SUB.LOAD_CLASS_ID,SUB.PROFILE_GROUP_ID,SUB.WEIGHT+TOTAL.TOTAL_WEIGHT AS WEIGHT from SUB
JOIN TOTAL
ON TOTAL.LOAD_CLASS_ID =SUB.LOAD_CLASS_ID
where SUB.row_num =1
UNION ALL
select LOAD_CLASS_ID,PROFILE_GROUP_ID,WEIGHT from SUB
where row_num >1 and row_num <5;