CREATE OR REPLACE VIEW DM_DATASCIENCE.V_LOAD_PROFILE_GROUP_AGG AS
WITH ABC AS
(select PROFILE_GROUP_ID,
(CASE WHEN SEASON like '%Autumn%' THEN 'Fall'
                  WHEN SEASON like '%Spring%' THEN 'Spring'
                  WHEN SEASON like '%Winter%' THEN 'Winter'
                  WHEN SEASON like '%Summer%' THEN 'Summer' END) AS SEASON,
(CASE WHEN DOW='WD' THEN PROFILE_ID ELSE NULL END) AS WEEKDAY_PROFILE_ID,
(CASE WHEN DOW='WE' THEN PROFILE_ID ELSE NULL END) AS WEEKEND_PROFILE_ID
FROM DM_DATASCIENCE.LOAD_PROFILE_GROUP
where DOW in ('WD','WE')
GROUP BY PROFILE_GROUP_ID,SEASON,DOW,PROFILE_ID)
select q1.PROFILE_GROUP_ID,q1.SEASON,q1.WEEKDAY_PROFILE_ID,q2.WEEKEND_PROFILE_ID
FROM ABC q1,ABC q2
where q1.PROFILE_GROUP_ID=q2.PROFILE_GROUP_ID
and q1.SEASON=q2.SEASON
and q1.WEEKDAY_PROFILE_ID is NOT NULL
and q2.WEEKEND_PROFILE_ID is NOT NULL;