CREATE OR REPLACE VIEW DM_DATASCIENCE.V_LOAD_PROFILE_HOLIDAY_PROFILE AS 
select US_HOLIDAY_DESC,PROFILE_ID,LP.SEASON,PROFILE_GROUP_ID from DM_DATASCIENCE.LOAD_PROFILE_GROUP LP
inner join WAREHOUSE.HUB_CALENDAR_DAY CD
on LP.SEASON=CD.SEASON
where LP.DOW='HO' and CD.YEAR = YEAR(CURRENT_DATE) and US_HOLIDAY_IND ='Holiday';