USE role OLAP_RW;
CREATE OR REPLACE SEQUENCE finance.CR_BUDGET_HR_USERS_GRPS_SEQ START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE finance.CR_BUDGET_GROUPS_HR_SEQ START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE finance.CR_BUDGET_HR_GROUPS_SECURITY_SEQ START = 1 INCREMENT = 1;
