delete from ACCELERATOR.TABLE_LIST
where TABLE_NAME IN ('CR_BALANCES','PS_CLASS_CF_TBL','PS_GL_ACCOUNT_TBL');

INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_BALANCES', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');

INSERT INTO ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('SUPPLY_CHAIN', 'PSOFTFIN', 'SUPPLY_CHAIN', 'PS_CLASS_CF_TBL', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');


INSERT INTO ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('SUPPLY_CHAIN', 'PSOFTFIN', 'SUPPLY_CHAIN', 'PS_GL_ACCOUNT_TBL', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');



