INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_BUDGET_LABOR_RESOURCE', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'COST_ELEMENT', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'COMPANY_SETUP', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_BUDGET_APPROVAL', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_BUDGET_VERSION_SECURITY', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_BUDGET_VERSION_SECURITY_ALL', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_COMPANY_SECURITY', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_DD_REQUIRED_FILTER', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_DEBIT_CREDIT', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_INTER_COMPANY', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_MISCELLANEOUS_JOURNALS', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_PP_TRUEUP', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_PURCHASING', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_REVERSALS_MANUAL', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_STRUCTURE_VALUES2', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_STRUCTURES_FLATTENED2', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'DEPARTMENT', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'EXPENDITURE_TYPE', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'JOB_TASK', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'PGE_CR_ACCOUNT', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'PGE_CR_ACCT_WO', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'PGE_CR_ATTRIBUTE1', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'PGE_CR_BUSINESS_UNIT', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'PGE_CR_COST_ELM', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'PGE_CR_DEPARTMENT_SECURITY', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'PGE_CR_DEPT_ID', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'PGE_CR_FIELD_WO', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'PGE_CR_OPERATING_UNIT', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'PGE_CR_REC_DEPT_ID', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'PP_SECURITY_USERS', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'PP_SECURITY_USERS_GROUPS', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'PP_TABLE_MONTHS', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'WO_DOC_JUSTIFICATION', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'WO_DOCUMENTATION', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'WORK_ORDER_CLASS_CODE', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'WORK_ORDER_CONTROL', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'WORKFLOW_DETAIL', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'ASSET_LOCATION', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'BUDGET_PLANT_CLASS', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'BUDGET_VERSION_FUND_PROJ', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'BUSINESS_SEGMENT', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_SOURCES', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'ESTIMATE_CHARGE_TYPE', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'FUNC_CLASS', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'GL_ACCOUNT', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'MAJOR_LOCATION', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'PGE_USERS_STG_IN', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'WORK_ORDER_ACCOUNT', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'WORK_ORDER_APPROVAL', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'WORK_ORDER_INITIATOR', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'WORK_ORDER_STATUS', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'WORK_ORDER_TYPE', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'BUDGET_VERSION_CONTROL', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'BUDGET_VERSION_SECURITY', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'BUDGET_VERSION_SECURITY_ALL', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'PP_COMPANY_SECURITY', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'PP_COMPANY_SECURITY_TEMP', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_JOURNALS', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'PGE_CR_OM_JUSTIFICATION_SUM', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_APPROVAL_STATUS', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_BUDGET_USERS_VALID_VALUES', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_BUDGET_VERSION', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'UPDATE_WITH_ACTUALS_EXCLUSION', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_BUDGET_HR_USERS_GRPS', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_BUDGET_GROUPS_HR', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_BUDGET_HR_GROUPS_SECURITY', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_ACCOUNT_TYPE', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_ALLOC_SYSTEM_CONTROL', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('SUPPLY_CHAIN', 'PSOFTFIN', 'SUPPLY_CHAIN', 'PS_VENDOR', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('SUPPLY_CHAIN', 'PSOFTFIN', 'SUPPLY_CHAIN', 'PS_AP_MTCH_EXCPTN', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('SUPPLY_CHAIN', 'PSOFTFIN', 'SUPPLY_CHAIN', 'PS_PYMT_TRMS_HDR', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('SUPPLY_CHAIN', 'PSOFTFIN', 'SUPPLY_CHAIN', 'PSOPRDEFN', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('SUPPLY_CHAIN', 'PSOFTFIN', 'SUPPLY_CHAIN', 'PS_ROLEXLATOPR', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('SUPPLY_CHAIN', 'PSOFTFIN', 'SUPPLY_CHAIN', 'PS_PERSONAL_DATA', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('SUPPLY_CHAIN', 'PSOFTFIN', 'SUPPLY_CHAIN', 'PS_SET_CNTRL_REC', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('SUPPLY_CHAIN', 'PSOFTFIN', 'SUPPLY_CHAIN', 'PS_EX_EXP_MTHD_TBL', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('SUPPLY_CHAIN', 'PSOFTFIN', 'SUPPLY_CHAIN', 'PS_EX_APRVL_HIST', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('SUPPLY_CHAIN', 'PSOFTFIN', 'SUPPLY_CHAIN', 'PS_EX_VIS_MCG_MAP', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('SUPPLY_CHAIN', 'PSOFTFIN', 'SUPPLY_CHAIN', 'PS_AP_MTCH_RULES', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('SUPPLY_CHAIN', 'PSOFTFIN', 'SUPPLY_CHAIN', 'PS_DEPT_TBL', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('SUPPLY_CHAIN', 'PSOFTFIN', 'SUPPLY_CHAIN', 'PS_EX_SHEET_HDR', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('SUPPLY_CHAIN', 'PSOFTFIN', 'SUPPLY_CHAIN', 'PS_EX_SHEET_PYMNT', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('SUPPLY_CHAIN', 'PSOFTFIN', 'SUPPLY_CHAIN', 'PSXLATITEM', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('SUPPLY_CHAIN', 'PSOFTFIN', 'SUPPLY_CHAIN', 'PSXLATITEMLANG', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('SUPPLY_CHAIN', 'PSOFTFIN', 'SUPPLY_CHAIN', 'PS_EX_CCET_MAP_TBL', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('SUPPLY_CHAIN', 'PSOFTFIN', 'SUPPLY_CHAIN', 'PS_EX_TYPES_TBL', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_AMOUNT_TYPE', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('SUPPLY_CHAIN', 'PSOFTFIN', 'SUPPLY_CHAIN', 'PS_JRNL_HEADER', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_ACCOUNTS_PAYABLE', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_ACCOUNTS_RECEIVABLE', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_ALLOCATIONS', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_BUDGET_DATA', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_BUDGET_DATA_ENTRY', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_CONVERSION', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_COST_REPOSITORY', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_EXPENSE', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_GL', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_INVENTORY', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_JOURNAL_LINES', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_PAYROLL', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_POWERPLANT', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_POWERTAX', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_TCS', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CWIP_CHARGE', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'PGE_CR_BUDGET_LABOR_RESOURCE', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'PGE_CR_OM_VAR_COMMENT', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'WO_EST_MONTHLY', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('SUPPLY_CHAIN', 'PSOFTFIN', 'SUPPLY_CHAIN', 'PS_DISTRIB_LINE', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('SUPPLY_CHAIN', 'PSOFTFIN', 'SUPPLY_CHAIN', 'PS_EX_SHEET_DIST', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('SUPPLY_CHAIN', 'PSOFTFIN', 'SUPPLY_CHAIN', 'PS_EX_SHEET_LINE', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('SUPPLY_CHAIN', 'PSOFTFIN', 'SUPPLY_CHAIN', 'PS_EX_TRANS', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('SUPPLY_CHAIN', 'PSOFTFIN', 'SUPPLY_CHAIN', 'PS_JOB', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('SUPPLY_CHAIN', 'PSOFTFIN', 'SUPPLY_CHAIN', 'PS_PO_HDR', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('SUPPLY_CHAIN', 'PSOFTFIN', 'SUPPLY_CHAIN', 'PS_PO_LINE', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('SUPPLY_CHAIN', 'PSOFTFIN', 'SUPPLY_CHAIN', 'PS_PO_LINE_DISTRIB', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('SUPPLY_CHAIN', 'PSOFTFIN', 'SUPPLY_CHAIN', 'PS_PO_LINE_SHIP', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('SUPPLY_CHAIN', 'PSOFTFIN', 'SUPPLY_CHAIN', 'PS_PYMNT_VCHR_XREF', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('SUPPLY_CHAIN', 'PSOFTFIN', 'SUPPLY_CHAIN', 'PS_RECV_HDR', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('SUPPLY_CHAIN', 'PSOFTFIN', 'SUPPLY_CHAIN', 'PS_RECV_LN_SHIP', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('SUPPLY_CHAIN', 'PSOFTFIN', 'SUPPLY_CHAIN', 'PS_RECV_LN_SHP_MTH', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('SUPPLY_CHAIN', 'PSOFTFIN', 'SUPPLY_CHAIN', 'PS_REQ_HDR', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('SUPPLY_CHAIN', 'PSOFTFIN', 'SUPPLY_CHAIN', 'PS_VCHR_MTCH_DETLS', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('SUPPLY_CHAIN', 'PSOFTFIN', 'SUPPLY_CHAIN', 'PS_VOUCHER', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('SUPPLY_CHAIN', 'PSOFTFIN', 'SUPPLY_CHAIN', 'PS_VOUCHER_LINE', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('SUPPLY_CHAIN', 'PSOFTFIN', 'SUPPLY_CHAIN', 'PS_JRNL_LN', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');


