Delete from accelerator.table_list
where target_schema = 'OUTAGEMANAGEMENT'
and   TABLE_NAME in ('CES_CUSTOMERS_REPLICATION');

insert into accelerator.table_list (SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG , DELETE_FLAG) Values 
('OMS','PGE_NMS','OUTAGEMANAGEMENT','CES_CUSTOMERS_REPLICATION','CSV','Y','N','Y','N','Y','Y','Y','Y','Y','N');