delete from ACCELERATOR.TABLE_LIST
where TARGET_SCHEMA = 'GEOSPATIAL'
and table_name in ('TRANSMISSIONSTRUCTURE_EVW', 'TRANSFORMER_EVW', 'SUPPORTSTRUCTURE_EVW', 'OPENPOINT_EVW', 'VOLTAGEREGULATOR_EVW', 'DYNAMICPROTECTIVEDEVICE_EVW', 'T_OPENPOINT_EVW', 'AIRCRAFTOBSTRUCTIONLIGHT_EVW', 'MISCNETWORKFEATURE_EVW', 'T_SWITCH_EVW', 'PFCORRECTINGEQUIPMENT_EVW', 'SWITCH_EVW', 'STREETLIGHT_EVW', 'FUSE_EVW', 'SERVICEPOINT_EVW');

insert into ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA ,TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG,
TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG, DELETE_FLAG, REPLICATION_TYPE, XYCOLS)
values
('GIS','TD','GEOSPATIAL','TRANSMISSIONSTRUCTURE_EVW','CSV','Y','N','Y','N','Y','Y','Y','Y','Y','N','Matillion',NULL),
('GIS','TD','GEOSPATIAL','TRANSFORMER_EVW', 'CSV','Y','N','Y','N','Y','Y','Y','Y','Y','N','Matillion','XCOORDINATE,YCOORDINATE'),
('GIS','TD','GEOSPATIAL','SUPPORTSTRUCTURE_EVW', 'CSV','Y','N','Y','N','Y','Y','Y','Y','Y','N','Matillion', NULL),
('GIS','TD','GEOSPATIAL','OPENPOINT_EVW','CSV','Y','N','Y','N','Y','Y','Y','Y','Y','N','Matillion','XCOORDINATE,YCOORDINATE'),
('GIS','TD','GEOSPATIAL','VOLTAGEREGULATOR_EVW','CSV','Y','N','Y','N','Y','Y','Y','Y','Y','N','Matillion','XCOORDINATE,YCOORDINATE'),
('GIS','TD','GEOSPATIAL','DYNAMICPROTECTIVEDEVICE_EVW','CSV','Y','N','Y','N','Y','Y','Y','Y','Y','N','Matillion','XCOORDINATE,YCOORDINATE'),
('GIS','TD','GEOSPATIAL','T_OPENPOINT_EVW','CSV','Y','N','Y','N','Y','Y','Y','Y','Y','N','Matillion','XCOORDINATE,YCOORDINATE'),
('GIS','TD','GEOSPATIAL','AIRCRAFTOBSTRUCTIONLIGHT_EVW','CSV','Y','N','Y','N','Y','Y','Y','Y','Y','N','Matillion','XCOORDINATE,YCOORDINATE'),
('GIS','TD','GEOSPATIAL','MISCNETWORKFEATURE_EVW','CSV','Y','N','Y','N','Y','Y','Y','Y','Y','N','Matillion','XCOORDINATE,YCOORDINATE'),
('GIS','TD','GEOSPATIAL','T_SWITCH_EVW','CSV','Y','N','Y','N','Y','Y','Y','Y','Y','N','Matillion','XCOORDINATE,YCOORDINATE'),
('GIS','TD','GEOSPATIAL','PFCORRECTINGEQUIPMENT_EVW','CSV','Y','N','Y','N','Y','Y','Y','Y','Y','N','Matillion','XCOORDINATE,YCOORDINATE'),
('GIS','TD','GEOSPATIAL','SWITCH_EVW','CSV','Y','N','Y','N','Y','Y','Y','Y','Y','N','Matillion','XCOORDINATE,YCOORDINATE'),
('GIS','TD','GEOSPATIAL','STREETLIGHT_EVW','CSV','Y','N','Y','N','Y','Y','Y','Y','Y','N','Matillion','XCOORDINATE,YCOORDINATE'),
('GIS','TD','GEOSPATIAL','FUSE_EVW','CSV','Y','N','Y','N','Y','Y','Y','Y','Y','N','Matillion','XCOORDINATE,YCOORDINATE'),
('GIS','TD','GEOSPATIAL','SERVICEPOINT_EVW','CSV','Y','N','Y','N','Y','Y','Y','Y','Y','N','Matillion','XCOORDINATE,YCOORDINATE');
