delete from ACCELERATOR.TABLE_LIST
where TABLE_NAME IN ('PP_SECURITY_USERS','DEPARTMENT','PGE_CR_DEPT_ID','PP_SECURITY_USERS_GROUPS','PGE_USERS_STG_IN','CR_COMPANY_SECURITY','PGE_CR_DEPARTMENT_SECURITY');

INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'PP_SECURITY_USERS', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');

INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'DEPARTMENT', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');

INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'PGE_CR_DEPT_ID', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');

INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'PP_SECURITY_USERS_GROUPS', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');

INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'PGE_USERS_STG_IN', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');

INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'CR_COMPANY_SECURITY', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');

INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'PGE_CR_DEPARTMENT_SECURITY', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y');