delete from ACCELERATOR.TABLE_LIST
where TARGET_SCHEMA = 'GEOSPATIAL'
and table_name in ('TRANSMISSIONSTRUCTURE','TRANSFORMER','SUPPORTSTRUCTURE','OPENPOINT','VOLTAGEREGULATOR','DYNAMICPROTECTIVEDEVICE','T_OPENPOINT','AIRCRAFTOBSTRUCTIONLIGHT','MISCNETWORKFEATURE','T_SWITCH','PFCORRECTINGEQUIPMENT','SWITCH','STREETLIGHT','FUSE');

insert into ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA ,TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG,
TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG, DELETE_FLAG, REPLICATION_TYPE, XYCOLS)
values
('GIS','TD','GEOSPATIAL','TRANSMISSIONSTRUCTURE','CSV','Y','N','Y','N','Y','Y','Y','Y','Y','N','Matillion',NULL),
('GIS','TD','GEOSPATIAL','TRANSFORMER', 'CSV','Y','N','Y','N','Y','Y','Y','Y','Y','N','Matillion','XCOORDINATE,YCOORDINATE'),
('GIS','TD','GEOSPATIAL','SUPPORTSTRUCTURE', 'CSV','Y','N','Y','N','Y','Y','Y','Y','Y','N','Matillion', NULL),
('GIS','TD','GEOSPATIAL','OPENPOINT','CSV','Y','N','Y','N','Y','Y','Y','Y','Y','N','Matillion','XCOORDINATE,YCOORDINATE'),
('GIS','TD','GEOSPATIAL','VOLTAGEREGULATOR','CSV','Y','N','Y','N','Y','Y','Y','Y','Y','N','Matillion','XCOORDINATE,YCOORDINATE'),
('GIS','TD','GEOSPATIAL','DYNAMICPROTECTIVEDEVICE','CSV','Y','N','Y','N','Y','Y','Y','Y','Y','N','Matillion','XCOORDINATE,YCOORDINATE'),
('GIS','TD','GEOSPATIAL','T_OPENPOINT','CSV','Y','N','Y','N','Y','Y','Y','Y','Y','N','Matillion','XCOORDINATE,YCOORDINATE'),
('GIS','TD','GEOSPATIAL','AIRCRAFTOBSTRUCTIONLIGHT','CSV','Y','N','Y','N','Y','Y','Y','Y','Y','N','Matillion','XCOORDINATE,YCOORDINATE'),
('GIS','TD','GEOSPATIAL','MISCNETWORKFEATURE','CSV','Y','N','Y','N','Y','Y','Y','Y','Y','N','Matillion','XCOORDINATE,YCOORDINATE'),
('GIS','TD','GEOSPATIAL','T_SWITCH','CSV','Y','N','Y','N','Y','Y','Y','Y','Y','N','Matillion','XCOORDINATE,YCOORDINATE'),
('GIS','TD','GEOSPATIAL','PFCORRECTINGEQUIPMENT','CSV','Y','N','Y','N','Y','Y','Y','Y','Y','N','Matillion','XCOORDINATE,YCOORDINATE'),
('GIS','TD','GEOSPATIAL','SWITCH','CSV','Y','N','Y','N','Y','Y','Y','Y','Y','N','Matillion','XCOORDINATE,YCOORDINATE'),
('GIS','TD','GEOSPATIAL','STREETLIGHT','CSV','Y','N','Y','N','Y','Y','Y','Y','Y','N','Matillion','XCOORDINATE,YCOORDINATE'),
('GIS','TD','GEOSPATIAL','FUSE','CSV','Y','N','Y','N','Y','Y','Y','Y','Y','N','Matillion','XCOORDINATE,YCOORDINATE');