ALTER TABLE DM_DATASCIENCE.EMISSIONS
DROP COLUMN LOAD_TIMESTAMP;

ALTER TABLE DM_DATASCIENCE.EMISSIONS
ADD (TRANSACTION_TYPE VARCHAR(40),ETL_INSERT_DTTM TIMESTAMP_NTZ(9) ,ETL_UPDATE_DTTM TIMESTAMP_NTZ(9));