create or replace TABLE DM_CUSTOMER.AR_AGING
 (
  FISCAL_YEAR       VARCHAR(20)         ,
  ACCOUNTING_PERIOD VARCHAR(20)         ,
  SNAPSHOT_DT       DATE                ,
  ACCOUNTING_DT     DATE                ,
  SA_ID             VARCHAR(30)         ,
  ACCT_ID           VARCHAR(30)         ,
  PER_ID            VARCHAR(30)         ,
  PREM_ID           VARCHAR(30)         ,
  RATE_CD           VARCHAR(30)         ,
  CURRENCY_CD       VARCHAR(3)          ,
  CURR_BAL_AMT      NUMBER(27,2)        ,
  PAYOFF_BAL_AMT    NUMBER(27,2)        ,
  UNBILLED_AMT      NUMBER(27,2)        ,
  BUCKET_0_30       NUMBER(27,2)        ,
  BUCKET_31_60      NUMBER(27,2)        ,
  BUCKET_61_90      NUMBER(27,2)        ,
  BUCKET_91_120     NUMBER(27,2)        ,
  BUCKET_121_PLUS   NUMBER(27,2)        ,
  BUCKET_121_150    NUMBER(27,2)        ,
  BUCKET_151_180    NUMBER(27,2)        ,
  BUCKET_181_210    NUMBER(27,2)        ,
  BUCKET_211_PLUS   NUMBER(27,2)        ,
  UNAPPLIED_AMT     NUMBER(27,2)        ,
  BUDGET_VAR_AMT    NUMBER(27,2)        ,
  ETL_CREATE_TIMESTAMP TIMESTAMP_NTZ(9),
  ETL_UPDATE_TIMESTAMP TIMESTAMP_NTZ(9),
  LOADED_BY 		VARCHAR(100)	   ,
  PRIMARY KEY(FISCAL_YEAR,ACCOUNTING_PERIOD,SNAPSHOT_DT,SA_ID,ACCOUNTING_DT)
 );
 
