create or replace TABLE DM_CUSTOMER.AR_CREDIT_BALANCES
 (
  FISCAL_YEAR			VARCHAR(20),
  ACCOUNTING_PERIOD		VARCHAR(20),
  ACCT_ID				VARCHAR(50),
  PAYOFF_AMT			NUMBER(27,2),
  ETL_CREATE_TIMESTAMP TIMESTAMP_NTZ(9),
  ETL_UPDATE_TIMESTAMP TIMESTAMP_NTZ(9),
  LOADED_BY 			VARCHAR(100),
  PRIMARY KEY (FISCAL_YEAR,ACCOUNTING_PERIOD,ACCT_ID)
 );
 

