create or replace TABLE DM_CUSTOMER.CASH_RECON
 (
  FISCAL_YEAR       VARCHAR(20)         ,
  ACCOUNTING_PERIOD VARCHAR(20)         ,
  ACCT_ID           VARCHAR(25)         ,
  NAME              VARCHAR(500)        ,
  PAY_ID            VARCHAR(25)         ,
  ADJ_ID            VARCHAR(25)         ,
  FT_ID             VARCHAR(25)         ,
  FT_TYPE           VARCHAR(25)         ,
  GL_DIVISION       VARCHAR(25)         ,
  DST_CD            VARCHAR(50)         ,
  GL_ACCT           VARCHAR(100)        ,
  GL_AMOUNT         NUMBER(25,2)        ,
  ACCOUNTING_DT     DATE                ,
  DST_CD_EFFDT      DATE                ,
  XFER_TO_GL_DT     DATE                ,
  BATCH_NBR         VARCHAR(25)         ,
  TNDR_CTL_ID       VARCHAR(25)         ,
  END_BALANCE       NUMBER(25,2)        ,
  PAY_TENDER_ID     VARCHAR(25)         ,
  TENDER_TYPE_CD    VARCHAR(25)         ,
  TENDER_AMT        NUMBER(25,2)        ,
  TNDR_SOURCE_CD    VARCHAR(25)         ,
  CHECK_NBR         VARCHAR(50)         ,
  CHAR_TYPE_CD      VARCHAR(25)         ,
  TYPE_DESCR        VARCHAR(500)        ,
  TNDR_CHAR_VAL     VARCHAR(500)        ,
  ADHOC_CHAR_VAL    VARCHAR(500)        ,
  ETL_CREATE_TIMESTAMP TIMESTAMP_NTZ(9) ,
  ETL_UPDATE_TIMESTAMP TIMESTAMP_NTZ(9) ,
  LOADED_BY 		VARCHAR(100)		,
  PRIMARY KEY(FISCAL_YEAR,ACCOUNTING_PERIOD,FT_ID,GL_ACCT,DST_CD,ACCOUNTING_DT,BATCH_NBR,TNDR_CTL_ID,PAY_TENDER_ID,TENDER_TYPE_CD,TNDR_SOURCE_CD,TNDR_CHAR_VAL,ADHOC_CHAR_VAL)
 )
;