create or replace TABLE DM_CUSTOMER.CUSTOMER_COUNT
 (
--  LOAD_TIMESTAMP    TIMESTAMP_NTZ(9)   ,
  FISCAL_YEAR		VARCHAR(20),
  ACCOUNTING_PERIOD	VARCHAR(20),
  PGE_ESS_GRP		VARCHAR(250),
  REVENUE_CLASS		VARCHAR(10),
  TAXING_CITY		VARCHAR(250),
  TAXING_COUNTY		VARCHAR(250),
  TINC				VARCHAR(250),
  BILL_CYCLE		VARCHAR(100),
  RATE_SCHED		VARCHAR(50),
  RATEVOLTAGE		VARCHAR(50),
  CUSTOMER_COUNT	NUMBER(25),
  ETL_CREATE_TIMESTAMP TIMESTAMP_NTZ(9),
  ETL_UPDATE_TIMESTAMP TIMESTAMP_NTZ(9),
  LOADED_BY 		VARCHAR(100),
  PRIMARY KEY (FISCAL_YEAR,ACCOUNTING_PERIOD,PGE_ESS_GRP,REVENUE_CLASS,TAXING_CITY,TAXING_COUNTY,TINC,BILL_CYCLE,RATE_SCHED,RATEVOLTAGE)
 );

