create or replace TABLE DM_CUSTOMER.DEPOSITS
 (
  FISCAL_YEAR           VARCHAR(20)    ,
  ACCOUNTING_PERIOD     VARCHAR(20)    ,
  DEPOSIT_TYPE          VARCHAR(100)   ,
  DEPOSIT_CHARGED       NUMBER(27,2)   ,
  ADJUSTMENT_TO_DEPOSIT NUMBER(27,2)   ,
  DEPOSIT_APPLIED       NUMBER(27,2)   ,
  DEPOSIT_REFUNDED      NUMBER(27,2)   ,
  DEPOSIT_LIABILITY     NUMBER(27,2)   ,
  ETL_CREATE_TIMESTAMP 	TIMESTAMP_NTZ(9),
  ETL_UPDATE_TIMESTAMP 	TIMESTAMP_NTZ(9),
  LOADED_BY 			VARCHAR(100)	,
  PRIMARY KEY(FISCAL_YEAR,ACCOUNTING_PERIOD,DEPOSIT_TYPE)
 );