CREATE OR replace external TABLE weather.ext_noaa_measurement_hist_temp
(station	VARCHAR(50)	 AS 	cast(value ['c1'] AS VARCHAR(50)),
year	NUMBER(4)	 AS 	cast(value ['c2'] AS NUMBER(4)),
month	NUMBER(2)	 AS 	cast(value ['c3'] AS NUMBER(2)),
day		NUMBER(2)	 AS 	cast(value ['c4'] AS NUMBER(2)),
temp_f	FLOAT	 AS 	cast(value ['c5'] AS FLOAT),
count_temp		NUMBER(2)	 AS 	cast(value ['c6'] AS NUMBER(2)),
dewpoint	FLOAT	 AS 	cast(value ['c7'] AS FLOAT),
count_dewp		NUMBER(2)	 AS 	cast(value ['c8'] AS NUMBER(2)),
slp	FLOAT	 AS 	cast(value ['c9'] AS FLOAT),
count_slp		NUMBER(2)	 AS 	cast(value ['c10'] AS NUMBER(2)),
stp	FLOAT	 AS 	cast(value ['c11'] AS FLOAT),
count_stp		NUMBER(2)	 AS 	cast(value ['c12'] AS NUMBER(2)),
visib	FLOAT	 AS 	cast(value ['c13'] AS FLOAT),
count_visib		NUMBER(2)	 AS 	cast(value ['c14'] AS NUMBER(2)),
wdsp	FLOAT	 AS 	cast(value ['c15'] AS FLOAT),
count_wdsp		NUMBER(2)	 AS 	cast(value ['c16'] AS NUMBER(2)),
mxpsd	FLOAT	 AS 	cast(value ['c17'] AS FLOAT),
gust	FLOAT	 AS 	cast(value ['c18'] AS FLOAT),
max_temp_f	FLOAT	 AS 	cast(value ['c19'] AS FLOAT),
min_temp_f  FLOAT	 AS 	cast(value ['c21'] AS FLOAT),
prcp  FLOAT	 AS 	cast(value ['c23'] AS FLOAT),
sndp  FLOAT	 AS 	cast(value ['c25'] AS FLOAT),
fog		NUMBER(1)	 AS 	cast(value ['c26'] AS NUMBER(1)),
rain_drizzle		NUMBER(1)	 AS 	cast(value ['c27'] AS NUMBER(1)),
snow_ice_pellets		NUMBER(1)	 AS 	cast(value ['c28'] AS NUMBER(1)),
hail		NUMBER(1)	 AS 	cast(value ['c29'] AS NUMBER(1)),
thunder		NUMBER	 AS 	cast(value ['c30'] AS NUMBER),
tornado_funnel_cloud		NUMBER	 AS 	cast(value ['c31'] AS NUMBER)
)
LOCATION=@public.DMS_S3_Source_data_enc/Datalake_Raw/Weather/Noaa/measurement/NOAA_HIST 
 REFRESH_ON_CREATE = true AUTO_REFRESH = true FILE_FORMAT = (TYPE = CSV SKIP_HEADER =1); 