create or replace TABLE DM_CUSTOMER.FT_WITH_NO_GL
 (
  LOAD_TIMESTAMP 	TIMESTAMP_NTZ(9)    ,
  FISCAL_YEAR       VARCHAR(20)         ,
  ACCOUNTING_PERIOD VARCHAR(20)         ,
  ACCOUNTING_DT     DATE                ,
  SA_CAT            VARCHAR(250)        ,
  AMOUNT_DUE        NUMBER(25,2)        ,
  CURRENT_BALANCE   NUMBER(25,2)        ,
  PAYOFF_BALANCE    NUMBER(25,2)        ,
  BUDGET_VARIANCE   NUMBER(25,2)        ,
  UNAPPLIED_PAYMENT NUMBER(25,2)        ,
  ENERGYASST_AMT    NUMBER(25,2)        ,
  ETL_CREATE_TIMESTAMP TIMESTAMP_NTZ(9) ,
  ETL_UPDATE_TIMESTAMP TIMESTAMP_NTZ(9) ,
  LOADED_BY 		VARCHAR(100)		,
  PRIMARY KEY (FISCAL_YEAR,ACCOUNTING_PERIOD,ACCOUNTING_DT,SA_CAT)
 );