delete from ACCELERATOR.TABLE_LIST where TABLE_NAME in ('WORKFLOW','APPROVAL_STATUS');

INSERT INTO ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'WORKFLOW', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');

INSERT INTO ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG)
VALUES('FINANCE', 'PWRPLANT', 'FINANCE', 'APPROVAL_STATUS', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');