INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG, DELETE_FLAG)
VALUES('SUPPLY_CHAIN', 'PSOFTFIN', 'SUPPLY_CHAIN', 'PS_RECV_LN_DISTRIB', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG, DELETE_FLAG)
VALUES('SUPPLY_CHAIN', 'PSOFTFIN', 'SUPPLY_CHAIN', 'PS_PAYMENT_TBL', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N');