USE role ACCOUNTADMIN;
INSERT INTO "ACCELERATOR" ."TABLE_LIST" values('FINANCE', 'CR_BUDGET_HR_USERS_GRPS', 'PARQUET', 'Y', 'Y', 'Y', 'Y');
INSERT INTO "ACCELERATOR" ."TABLE_LIST" values('FINANCE', 'CR_BUDGET_GROUPS_HR', 'PARQUET', 'Y', 'Y', 'Y', 'Y');
INSERT INTO "ACCELERATOR" ."TABLE_LIST" values('FINANCE', 'CR_BUDGET_HR_GROUPS_SECURITY', 'PARQUET', 'Y', 'Y', 'Y', 'Y');
