DELETE FROM ACCELERATOR.TABLE_LIST WHERE TARGET_SCHEMA = 'METER'  AND   TABLE_NAME IN ('F1_EXT_LOOKUP_VAL_L','CI_LOOKUP_VAL');

INSERT INTO ACCELERATOR.TABLE_LIST 
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG , DELETE_FLAG) 
VALUES ('MDM','CISADM','METER','F1_EXT_LOOKUP_VAL_L','CSV','Y','Y','Y','Y','Y','N','N','N','N','N');

INSERT INTO ACCELERATOR.TABLE_LIST 
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG , DELETE_FLAG) 
VALUES ('MDM','CISADM','METER','CI_LOOKUP_VAL','CSV','Y','Y','Y','Y','Y','N','N','N','N','N');