USE role ACCOUNTADMIN;

DELETE FROM "ACCELERATOR"."TABLE_LIST"
WHERE SCHEMA_NAME='FINANCE' and TABLE_NAME IN ('PGE_CR_OM_JUSTIFICATION_SUM','CR_APPROVAL_STATUS','CR_BUDGET_USERS_VALID_VALUES','CR_BUDGET_VERSION','UPDATE_WITH_ACTUALS_EXCLUSION','COST_CENTERS','POSITIONS','SUPERVISORY_ORGANIZATION','WORKER') ;

INSERT INTO "ACCELERATOR"."TABLE_LIST" values('FINANCE', 'PGE_CR_OM_JUSTIFICATION_SUM', 'PARQUET', 'Y', 'Y', 'Y', 'Y');
INSERT INTO "ACCELERATOR"."TABLE_LIST" values('FINANCE', 'CR_APPROVAL_STATUS', 'PARQUET', 'Y', 'Y', 'Y', 'Y');
INSERT INTO "ACCELERATOR"."TABLE_LIST" values('FINANCE', 'CR_BUDGET_USERS_VALID_VALUES', 'PARQUET', 'Y', 'Y', 'Y', 'Y');
INSERT INTO "ACCELERATOR"."TABLE_LIST" values('FINANCE', 'CR_BUDGET_VERSION', 'PARQUET', 'Y', 'Y', 'Y', 'Y');
INSERT INTO "ACCELERATOR"."TABLE_LIST" values('FINANCE', 'UPDATE_WITH_ACTUALS_EXCLUSION', 'PARQUET', 'Y', 'Y', 'Y', 'Y');



