delete from accelerator.table_list where TABLE_NAME in ('CI_TNDR_CTL','CI_PAY_TNDR_CHAR','CI_CHAR_TYPE_L','CI_FT_PROC','CI_BSEG_CALC','CI_BSEG_CALC_LN','CI_FT','CI_FT_GL','CI_PAY_CAN_RSN_L','CI_BSEG_SQ');
INSERT INTO ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG, DELETE_FLAG)
VALUES('CCB', 'CISADM', 'CUSTOMER', 'CI_FT_PROC', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N');
INSERT INTO ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG, DELETE_FLAG)
VALUES('CCB', 'CISADM', 'CUSTOMER', 'CI_TNDR_CTL', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N');
INSERT INTO ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG, DELETE_FLAG)
VALUES('CCB', 'CISADM', 'CUSTOMER', 'CI_PAY_TNDR_CHAR', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N');
INSERT INTO ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG, DELETE_FLAG)
VALUES('CCB', 'CISADM', 'CUSTOMER', 'CI_CHAR_TYPE_L', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'N');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG, DELETE_FLAG)
VALUES('CCB', 'CISADM', 'CUSTOMER', 'CI_BSEG_CALC', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG, DELETE_FLAG)
VALUES('CCB', 'CISADM', 'CUSTOMER', 'CI_FT', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG, DELETE_FLAG)
VALUES('CCB', 'CISADM', 'CUSTOMER', 'CI_FT_GL', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO  ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG, DELETE_FLAG)
VALUES('CCB', 'CISADM', 'CUSTOMER', 'CI_BSEG_CALC_LN', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG, DELETE_FLAG)
VALUES('CCB', 'CISADM', 'CUSTOMER', 'CI_PAY_CAN_RSN_L', 'PARQUET', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'N');
INSERT INTO ACCELERATOR.TABLE_LIST
(SOURCE_DB, SOURCE_SCHEMA, TARGET_SCHEMA, TABLE_NAME, FILE_TYPE, RUN_FLAG, EXT_TABLE_FLAG, SEQ_FLAG, VIEW_FLAG, LOAD_COL_FLAG, TRANS_TABLE_FLAG, TRANS_SWAP_STAGE_FLAG, TRANS_PIPE_FLAG, TRANS_TASK_FLAG, DELETE_FLAG)
VALUES('CCB', 'CISADM', 'CUSTOMER', 'CI_BSEG_SQ', 'CSV', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y');
insert into "ACCELERATOR"."ORACLE_SNOWFLAKE_TYPE_CONVERSION"
select 'TIMESTAMP(0)', 'TIMESTAMP'  where not exists (select 1 from "ACCELERATOR"."ORACLE_SNOWFLAKE_TYPE_CONVERSION" where ORACLE_DATATYPE = 'TIMESTAMP(0)');
update accelerator.table_list set RUN_FLAG= 'Y' where TABLE_NAME in ('CM_UR_SA') and RUN_FLAG= 'C';



