alter table DM_DATASCIENCE.OVERLOADED_TRANSFORMER_YEARLY add column XFMR_EV_COUNT NUMBER(38,0);
alter table DM_DATASCIENCE.OVERLOADED_TRANSFORMER_YEARLY add column XFMR_PV_SIZE NUMBER(38,0);
alter table DM_DATASCIENCE.OVERLOADED_TRANSFORMER_YEARLY add column XFMR_TYPE VARCHAR(16777216);
alter table DM_DATASCIENCE.OVERLOADED_TRANSFORMER_YEARLY_SNAPSHOT add column XFMR_EV_COUNT NUMBER(38,0);
alter table DM_DATASCIENCE.OVERLOADED_TRANSFORMER_YEARLY_SNAPSHOT add column XFMR_PV_SIZE NUMBER(38,0);
alter table DM_DATASCIENCE.OVERLOADED_TRANSFORMER_YEARLY_SNAPSHOT add column XFMR_TYPE VARCHAR(16777216);

