create or replace TABLE DM_CUSTOMER.RESIDENTIAL_CONS
 (
  FISCAL_YEAR             VARCHAR(20)  ,
  ACCOUNTING_PERIOD       VARCHAR(20)  ,
  CCB_SP_ID               VARCHAR(50)  ,
  ACCOUNTING_DT           DATE         ,
  WATER_HEAT_TYPE_GRP     VARCHAR(100) ,
  PREM_TYPE_GRP           VARCHAR(100) ,
  HEAT_TYPE_GRP           VARCHAR(100) ,
  TYPE_OF_USAGE           VARCHAR(100) ,
  CONSUMPTION_BLOCK       VARCHAR(100) ,
  SORT_CONS_BLOCK         NUMBER       ,
  CONSUMPTION_BLOCK_VALUE NUMBER       ,
  COUNT_SP_ID             NUMBER       ,
  BILLED_QTY              NUMBER(15,2) ,
  CALC_AMT                NUMBER(15,2) ,  
  ETL_CREATE_TIMESTAMP TIMESTAMP_NTZ(9),
  ETL_UPDATE_TIMESTAMP TIMESTAMP_NTZ(9),
  LOADED_BY VARCHAR(100)               ,
  PRIMARY KEY(FISCAL_YEAR,ACCOUNTING_PERIOD,CCB_SP_ID,ACCOUNTING_DT,WATER_HEAT_TYPE_GRP,PREM_TYPE_GRP,HEAT_TYPE_GRP,TYPE_OF_USAGE,CONSUMPTION_BLOCK,CONSUMPTION_BLOCK_VALUE)
 );
 
 