create or replace TABLE DM_CUSTOMER.REVENUE
 (
--  LOAD_TIMESTAMP    TIMESTAMP_NTZ(9)   ,
--  SNAPSHOT_DT       DATE               ,
  FISCAL_YEAR       VARCHAR(20)        ,
  ACCOUNTING_PERIOD VARCHAR(20)        ,
  TAXING_CITY       VARCHAR(250)       ,
  TAXING_COUNTY     VARCHAR(250)       ,
  PREM_INC          VARCHAR(250)       ,
  REVENUE_CLASS     VARCHAR(250)       ,
  PGE_ESS_GRP       VARCHAR(250)       ,
  SA_TYPE           VARCHAR(50)        ,
  RATE_SCHED        VARCHAR(20)        ,
  RATEVOLTAGE       VARCHAR(250)       ,
  BILL_CYC          VARCHAR(50)        ,
  REV_CUR_MONTH     NUMBER(25,2)       ,
  KWH_CUR_MONTH     NUMBER(25,2)       ,
  REV_YTD           NUMBER(25,2)       ,
  KWH_YTD           NUMBER(25,2)       ,
  AMT_CUR_MONTH     NUMBER(25,2)       ,
  AMT_YTD           NUMBER(25,2)       ,
  ETL_CREATE_TIMESTAMP TIMESTAMP_NTZ(9),
  ETL_UPDATE_TIMESTAMP TIMESTAMP_NTZ(9),
  LOADED_BY 		VARCHAR(100)	   ,
  PRIMARY KEY(FISCAL_YEAR,ACCOUNTING_PERIOD,TAXING_CITY,TAXING_COUNTY,PREM_INC,REVENUE_CLASS,PGE_ESS_GRP,SA_TYPE,RATE_SCHED,RATEVOLTAGE,BILL_CYC)
 );
 
