create or replace TABLE DM_CUSTOMER.SCH_115_LIA_BY_COUNTY
 (
  FISCAL_YEAR	VARCHAR(20),
  ACCOUNTING_PERIOD	VARCHAR(20),
  COUNTY	VARCHAR(200),
  RESIDENTIAL_AMT	NUMBER(27,2),
  NON_RESIDENTIAL_AMT	NUMBER(27,2),
  ETL_CREATE_TIMESTAMP TIMESTAMP_NTZ(9),
  ETL_UPDATE_TIMESTAMP TIMESTAMP_NTZ(9),
  LOADED_BY 		VARCHAR(100),
  PRIMARY KEY (FISCAL_YEAR,ACCOUNTING_PERIOD,COUNTY)
 );
 
