create or replace TABLE DM_CUSTOMER.UNBILLED_REVENUE
 (
  FISCAL_YEAR       VARCHAR(20)        ,
  ACCOUNTING_PERIOD VARCHAR(20)        ,
  BATCH_NBR         NUMBER(10)         ,
  BATCH_RUN_DT      DATE               ,
  ACCT_ID           VARCHAR(20)        ,
  BILL_CYC_CD       VARCHAR(20)        ,
  SA_ID             VARCHAR(20)        ,
  SP_ID             VARCHAR(20)        ,
  ACCT_REV_MONTH    VARCHAR(60)        ,
  BEGIN_DT          DATE               ,
  END_DT            DATE               ,
  CM_CUST_GRP       VARCHAR(60)        ,
  CM_UR_SA_STAT_FLG VARCHAR(20)        ,
  UBR_SA_STAT_DESCR VARCHAR(150)       ,
  SERVICE_TYPE      VARCHAR(100)       ,
  SA_TYPE_CD        VARCHAR(20)        ,
  CIS_DIVISION      VARCHAR(100)       ,
  RS_CD             VARCHAR(20)        ,
  CM_REV_CL_CD      VARCHAR(20)        ,
  CM_RATE_VOLTG     VARCHAR(20)        ,
  CM_USG_ST_DT TIMESTAMP_NTZ(9)        ,
  CM_USG_END_DT TIMESTAMP_NTZ(9)       ,
  CM_TAXING_CITY   VARCHAR(200)        ,
  CM_TAXING_COUNTY VARCHAR(200)        ,
  CM_CITY_INC      VARCHAR(200)        ,
  CM_TOT_REV       NUMBER(27,2)        ,
  CM_TOT_NONREV    NUMBER(27,2)        ,
  CM_TOT_UNB_CONS  NUMBER(27,2)        ,
  MESSAGE_CAT_NBR  NUMBER(15)          ,
  MESSAGE_NBR      NUMBER(15)          ,
  ETL_CREATE_TIMESTAMP TIMESTAMP_NTZ(9),
  ETL_UPDATE_TIMESTAMP TIMESTAMP_NTZ(9),
  LOADED_BY VARCHAR(100)               ,
  PRIMARY KEY(FISCAL_YEAR,ACCOUNTING_PERIOD,SA_ID,SP_ID,BATCH_NBR,CM_CUST_GRP,CM_UR_SA_STAT_FLG,UBR_SA_STAT_DESCR)
 );

	