delete From WAREHOUSE.DL_TASK_CTRL_INFO where target_tbname like 'PS_PAYMENT_TBL';
delete From WAREHOUSE.DL_TASK_CTRL_INFO where target_tbname like 'PS_RECV_LN_DISTRIB';
INSERT INTO  WAREHOUSE.DL_TASK_CTRL_INFO
(TARGET_TBNAME, WAREHOUSE_NAME, SCHEDULE, TARGET_SCHNAME, LANDING_SCHNAME, UNIQUE_KEY, DEL_FLAG)
VALUES('PS_RECV_LN_DISTRIB', 'DATA_INGESTION_FINANCE', 'USING CRON 0 0 * * * America/Los_Angeles', 'SUPPLY_CHAIN', 'LANDINGTEMP', 'BUSINESS_UNIT, RECEIVER_ID, RECV_LN_NBR, RECV_SHIP_SEQ_NBR, DISTRIB_LINE_NUM', 'Y');
INSERT INTO  WAREHOUSE.DL_TASK_CTRL_INFO
(TARGET_TBNAME, WAREHOUSE_NAME, SCHEDULE, TARGET_SCHNAME, LANDING_SCHNAME, UNIQUE_KEY, DEL_FLAG)
VALUES('PS_PAYMENT_TBL', 'DATA_INGESTION_FINANCE', 'USING CRON 0 0 * * * America/Los_Angeles', 'SUPPLY_CHAIN', 'LANDINGTEMP', 'BANK_SETID, BANK_CD, BANK_ACCT_KEY, PYMNT_ID', 'Y');
update ACCELERATOR.TABLE_LIST set RUN_FLAG = 'Y' where TABLE_NAME = 'PS_RECV_LN_DISTRIB';
update ACCELERATOR.TABLE_LIST set RUN_FLAG = 'Y' where TABLE_NAME = 'PS_PAYMENT_TBL';
